export const DEFAULT_CONFIG = {
  waitlist_claim_window_max_minutes: 120,
  waitlist_claim_window_min_minutes: 15,
  late_cancellation_threshold_hours: 12,
  host_late_cancellation_threshold_hours: 24,
  attendance_grace_period_hours: 2,
  attendance_confirmation_hours: 24,
  host_attendance_correction_window_hours: 48,
  left_swipe_suppression_days: 30,
  new_activity_boost_hours: 24,
  feed_bucket_shares: { familiar: 0.7, adjacent: 0.2, wildcard: 0.1 },
  feed_max_per_host: 3,
  feed_max_per_category: 5,
  group_dormancy_days: 90,
  guest_token_ttl_days_after_completion: 7,
  reliability_visibility_min_activities: 3,
  reliability_decay_months: 12,
  ranking_weights: {
    category_affinity: 0.25,
    tag_affinity: 0.1,
    proximity: 0.2,
    time_fit: 0.15,
    urgency: 0.1,
    host_reliability: 0.1,
    social_proof: 0.05,
    recency_penalty: 0.05,
  },
  session_generation_horizon_weeks: 4,
  travel_speed_kmh: 30,
} as const;
