export const stitchColors = {
  "inverse-surface": "#31302f",
  "surface-container-low": "#f6f3f1",
  "on-error": "#ffffff",
  "on-tertiary-container": "#ffbfc6",
  "on-tertiary-fixed-variant": "#792d3b",
  "on-surface": "#1c1c1a",
  "surface-container-highest": "#e5e2e0",
  "on-secondary-container": "#663500",
  "surface-container-lowest": "#ffffff",
  "on-secondary-fixed-variant": "#6e3900",
  "primary-fixed": "#a6f4b5",
  "surface-container": "#f0edeb",
  "primary-fixed-dim": "#8bd79b",
  secondary: "#904d00",
  "outline-variant": "#bfc9bd",
  "surface-variant": "#e5e2e0",
  surface: "#fcf9f6",
  "on-primary-container": "#93e0a2",
  "surface-bright": "#fcf9f6",
  "on-secondary-fixed": "#2f1500",
  outline: "#707a6f",
  "on-tertiary": "#ffffff",
  "on-error-container": "#93000a",
  "error-container": "#ffdad6",
  "primary-container": "#166534",
  "surface-dim": "#dcd9d7",
  "secondary-fixed-dim": "#ffb77d",
  "secondary-fixed": "#ffdcc3",
  "on-primary": "#ffffff",
  background: "#fcf9f6",
  "surface-container-high": "#ebe8e5",
  "surface-tint": "#1f6c3a",
  "inverse-on-surface": "#f3f0ee",
  tertiary: "#722736",
  "on-primary-fixed": "#00210b",
  "tertiary-container": "#8f3e4c",
  "on-surface-variant": "#404940",
  "tertiary-fixed-dim": "#ffb2bb",
  "tertiary-fixed": "#ffd9dd",
  "inverse-primary": "#8bd79b",
  "on-primary-fixed-variant": "#005226",
  "on-background": "#1c1c1a",
  "on-tertiary-fixed": "#3f0112",
  "on-secondary": "#ffffff",
  primary: "#004c22",
  error: "#ba1a1a",
  "secondary-container": "#fe932c",
} as const;

export const stitchTheme = {
  colors: stitchColors,
  borderRadius: {
    DEFAULT: "0.25rem",
    lg: "0.5rem",
    xl: "0.75rem",
    full: "9999px",
  },
  spacing: {
    gutter: "16px",
    "margin-mobile": "20px",
    sm: "8px",
    lg: "24px",
    base: "4px",
    md: "16px",
    xs: "4px",
    xl: "32px",
  },
  fontFamily: {
    sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
  },
} as const;
