import type { ActivitySummary, Group, JoinRequest, Message, UserProfile } from "@activity-match/shared";

export const demoProfile: UserProfile = {
  id: "demo-user",
  display_name: "Alex Morgan",
  avatar_ref: null,
  bio: "Always up for board games and outdoor adventures.",
  home_area_label: "St Paul's Bay",
  travel_radius_minutes: 20,
  date_of_birth: "1995-06-12",
  gender: "woman",
  verification_status: "verified",
  account_status: "active",
  locale: "en",
  timezone: "Europe/Malta",
  created_at: new Date().toISOString(),
};

export const demoActivities: ActivitySummary[] = [
  {
    id: "a1",
    title: "Tuesday Board Games Night",
    listing_type: "confirmed",
    status: "published",
    category: { id: "1", name: "Board Games", parent_id: null, is_active: true },
    starts_at: new Date(Date.now() + 86400000 * 2).toISOString(),
    duration_minutes: 180,
    area_label: "St Paul's Bay",
    distance_from_viewer_minutes: 12,
    cost_amount: 0,
    cost_currency: "EUR",
    skill_level: "any",
    capacity: 8,
    participation_count: 5,
    spaces_remaining: 3,
    is_full: false,
    is_joinable: true,
    host: { id: "h1", display_name: "Jamie", avatar_ref: null },
    tags: ["beginner-friendly", "social"],
  },
  {
    id: "a2",
    title: "Sunset Coastal Walk",
    listing_type: "confirmed",
    status: "published",
    category: { id: "3", name: "Outdoor Adventures", parent_id: null, is_active: true },
    starts_at: new Date(Date.now() + 86400000 * 5).toISOString(),
    duration_minutes: 90,
    area_label: "Sliema",
    distance_from_viewer_minutes: 18,
    cost_amount: 0,
    cost_currency: "EUR",
    skill_level: "beginner",
    capacity: 12,
    participation_count: 12,
    spaces_remaining: 0,
    is_full: true,
    is_joinable: false,
    host: { id: "h2", display_name: "Sam", avatar_ref: null },
    tags: ["outdoors", "casual"],
  },
  {
    id: "a3",
    title: "Weekend Padel Group",
    listing_type: "proposed",
    status: "published",
    category: { id: "2", name: "Sports & Fitness", parent_id: null, is_active: true },
    starts_at: null,
    duration_minutes: 90,
    area_label: "Valletta",
    distance_from_viewer_minutes: 25,
    cost_amount: 8,
    cost_currency: "EUR",
    skill_level: "intermediate",
    capacity: 4,
    participation_count: 2,
    spaces_remaining: 2,
    is_full: false,
    is_joinable: true,
    host: { id: "h3", display_name: "Taylor", avatar_ref: null },
    tags: ["competitive", "weekly"],
  },
];

export const demoRequests: JoinRequest[] = [
  {
    id: "r1",
    activity_id: "a1",
    user_id: "u1",
    status: "pending",
    introduction: "I love Catan and Ticket to Ride!",
    waitlist_position: null,
    claim_expires_at: null,
    created_at: new Date().toISOString(),
    user: { id: "u1", display_name: "Morgan", avatar_ref: null },
  },
];

export const demoMessages: Message[] = [
  {
    id: "m1",
    conversation_id: "c1",
    sender_user_id: null,
    type: "system",
    body: "Activity published. See you there!",
    payload: { system_type: "activity_published" },
    created_at: new Date(Date.now() - 3600000).toISOString(),
    edited_at: null,
  },
  {
    id: "m2",
    conversation_id: "c1",
    sender_user_id: "h1",
    type: "user_text",
    body: "Feel free to bring snacks to share!",
    payload: {},
    created_at: new Date(Date.now() - 1800000).toISOString(),
    edited_at: null,
  },
];

export const demoGroup: Group = {
  id: "g1",
  name: "Tuesday Board Games Group",
  description: "Weekly board game sessions for all levels.",
  category: { id: "1", name: "Board Games", parent_id: null, is_active: true },
  frequency: "weekly",
  preferred_days: ["tue"],
  target_size: 8,
  skill_level: "any",
  attendance_mode: "flexible",
  membership_state: "open",
  chat_persists_between_sessions: true,
  status: "active",
  member_count: 12,
  upcoming_sessions: [demoActivities[0]],
};
